# Generated by Django 5.1.3 on 2024-11-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='numero',
            field=models.CharField(max_length=10),
        ),
    ]
